### ISSUE TITLE
mismatched types using rspirv 0.5.4 on latest nightly rustc

### ISSUE THREAD

**Issue by carado** [gfx-rs/rspirv#122]
Hi,
When creating a simple project with the latest nightly rustc (1.43.0-nightly (823ff8cf1 2020-03-07)), cargo fails to build rspirv as a dependency due to a type mismatch.
```bash
carado@uwu:~/tmp/rust20 $ cargo init
     Created binary (application) package
carado@uwu:~/tmp/rust20 $ echo 'rspirv = "0.5.4"' >> Cargo.toml 
carado@uwu:~/tmp/rust20 $ cargo check
    Updating crates.io index
[…]
    Checking spirv_headers v1.4.2
[…]
    Checking rspirv v0.5.4
error[E0308]: mismatched types
   --> /home/carado/.cargo/registry/src/github.com-1ecc6299db9ec823/rspirv-0.5.4/mr/constructs.rs:190:22
    |
190 |             version: (spirv::MAJOR_VERSION << 16) | (spirv::MINOR_VERSION << 8),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rspirv`.
```

**Comment by kvark** [comment]
I'm a bit confused about how this passed CI to get in?..

**Comment by antiagainst** [comment]
Okay, this is another breaking issue from [v1.3.4](https://docs.rs/crate/spirv_headers/1.3.4/source/spirv.rs) to [v1.4.1](https://docs.rs/crate/spirv_headers/1.4.1/source/autogen_spirv.rs): the types of `MAJOR_VERSION`/`MINOR_VERSION` were changed. I should have caught that in code reviews.

rspirv 0.5.4 is expected to work with [spirv_headers v1.3](https://docs.rs/crate/rspirv/0.5.4/source/Cargo.toml). It's written as caret requirements because the header library should just strictly include more symbols instead of having breaking changes, but we have now.. I think we should publish a new v0.5.5 with tilde requirements for spirv_headers.

**Comment by antiagainst** [comment]
Actually, should go up to v0.6.0 with a bunch of breaking changes in rspirv itself. It might not be able to do anything regarding v0.5.4 anymore at the moment except yanking it.

**Comment by antiagainst** [comment]
Published v.6.0. Closing this one now.
